SPANISH_STOPWORDS = [
    'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'lo', 'al', 'del',
    'yo', 'me', 'mi', 'mí', 'conmigo', 'tú', 'te', 'ti', 'contigo', 'usted', 
    'vos', 'él', 'le', 'lo', 'la', 'se', 'sí', 'consigo', 'ella', 'ello', 
    'nosotros', 'nos', 'nosotras', 'vosotros', 'vosotras', 'os', 'ustedes',
    'ellos', 'ellas', 'les', 'los', 'las', 'se', 'sí', 'consigo',
    'a', 'ante', 'bajo', 'cabe', 'con', 'contra', 'de', 'desde', 'durante',
    'en', 'entre', 'hacia', 'hasta', 'mediante', 'para', 'por', 'según', 
    'sin', 'so', 'sobre', 'tras', 'versus', 'vía',
    'y', 'o', 'u', 'pero', 'mas', 'aunque', 'sino', 'porque', 'como', 'que',
    'si', 'cuando', 'mientras', 'donde', 'como', 'así', 'tal', 'tanto',
    'muy', 'mucho', 'poco', 'bastante', 'demasiado', 'más', 'menos', 'algo',
    'nada', 'todo', 'también', 'tampoco', 'siempre', 'nunca', 'jamás',
    'aún', 'ya', 'ahora', 'antes', 'después', 'luego', 'pronto', 'hoy',
    'ayer', 'mañana', 'siempre', 'nunca', 'tal', 'vez', 'quizá', 'quizás',
    'acá', 'allí', 'allá', 'cerca', 'lejos', 'arriba', 'abajo', 'adelante',
    'atrás', 'dentro', 'fuera', 'aquí', 'ahí', 'allá',
    'ser', 'estar', 'haber', 'tener', 'hacer', 'poder', 'decir', 'ir',
    'ver', 'dar', 'saber', 'querer', 'llegar', 'dejar', 'seguir', 'poner',
    'parecer', 'creer', 'hablar', 'llevar', 'encontrar', 'llamar', 'venir',
    'pensar', 'salir', 'volver', 'tomar', 'conocer', 'vivir', 'sentir',
    'tratar', 'mirar', 'esperar', 'buscar', 'existir', 'entrar', 'trabajar',
    'escribir', 'perder', 'producir', 'ocurrir', 'entender', 'pedir',
    'este', 'esta', 'esto', 'estos', 'estas', 'ese', 'esa', 'eso', 'esos',
    'esas', 'aquel', 'aquella', 'aquello', 'aquellos', 'aquellas',
    'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo',
    'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras',
    'vuestro', 'vuestra', 'vuestros', 'vuestras',
    'qué', 'quién', 'quiénes', 'cuál', 'cuáles', 'cómo', 'cuándo', 'dónde',
    'por qué', 'para qué',
    'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve',
    'diez', 'cien', 'mil', 'primer', 'primero', 'segundo', 'tercer', 'tercero',
    'así', 'así que', 'tal', 'cual', 'cuales', 'cualquier', 'cualquiera',
    'ningún', 'ninguno', 'ninguna', 'varios', 'varias', 'otro', 'otra',
    'otros', 'otras', 'mismo', 'misma', 'mismos', 'mismas', 'tan', 'tanto',
    'cada', 'solo', 'solamente', 'justo', 'siquiera', 'incluso', 'excepto',
    'además', 'incluso', 'hasta', 'desde', 'casi', 'según', 'viceversa',
    'etc', 'etcétera', 'aprox', 'aproximadamente', 'dijo', 'dice', 'dicen',
]