# Generated by Django 3.2.25 on 2025-05-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('missing_doc', 'Documentacion faltante'), ('pending', 'Pendiente de aprobacion'), ('rejected', 'Rechazada'), ('approved', 'Aprobada'), ('expired', 'Expirada')], max_length=100),
        ),
    ]
