# Generated by Django 3.2.25 on 2025-05-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_alter_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('min_advance_notice_days', models.IntegerField()),
                ('certificate_require', models.BooleanField(default=True)),
                ('tolerance_days_certificate_submission', models.IntegerField(blank=True, null=True)),
                ('total_days_granted', models.IntegerField(blank=True, null=True)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('yearly_approved_requests', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='healthfirstuser',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.licensetype'),
        ),
    ]
