# Generated by Django 3.2.25 on 2025-05-10 23:01
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0003_auto_20250506_1519'),
    ]

    operations = [
        
            migrations.AddField(
            model_name='license',
            name='evaluator',
            field=models.ForeignKey(default=None, blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
