# Generated by Django 3.2.25 on 2025-05-11 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0004_auto_20250510_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_License',
            fields=[
                ('type_license_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('min_advance_notice_days', models.IntegerField()),
                ('certificate_require', models.BooleanField(default=True)),
                ('tolerance_days_certificate_submission', models.IntegerField(blank=True, null=True)),
                ('total_days_granted', models.IntegerField(blank=True, null=True)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('yearly_approved_requests', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
