# Generated by Django 3.2.25 on 2025-06-16 18:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('model_type', models.CharField(choices=[('ANOMALY_DETECTION', 'Detección de anomalías'), ('CLASSIFICATION', 'Coherencia de certificados'), ('REGRESSION', 'Regresión'), ('HEALTH_RISK', 'Predicción de riesgo de salud'), ('LICENSE_APPROVAL', 'Aprobación de licencias'), ('REJECTION_REASON', 'Clasificación de motivo de rechazo')], max_length=50, verbose_name='Tipo de modelo')),
                ('algorithm', models.CharField(choices=[('ISOLATION_FOREST', 'Isolation Forest'), ('RANDOM_FOREST', 'Random Forest'), ('LOGISTIC_REGRESSION', 'Regresión Logística'), ('LGBM', 'LightGBM')], max_length=50, verbose_name='Algoritmo')),
                ('version', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('training_date', models.DateTimeField(verbose_name='Fecha de entrenamiento')),
                ('first_training_id', models.IntegerField(blank=True, help_text='ID del primer registro usado para entrenar el modelo', null=True, verbose_name='Primer ID de entrenamiento')),
                ('last_training_id', models.IntegerField(blank=True, help_text='ID del último registro usado para entrenar el modelo', null=True, verbose_name='Último ID de entrenamiento')),
            ],
            options={
                'verbose_name': 'Modelo de ML',
                'verbose_name_plural': 'Modelos de ML',
                'unique_together': {('name', 'version')},
            },
        ),
    ]
