# Generated by Django 3.2.25 on 2025-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_mlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('EMPLOYEE_ANOMALY_DETECTION', 'Detección de anomalías de empleados'), ('SUPERVISOR_ANOMALY_DETECTION', 'Detección de anomalías'), ('CLASSIFICATION', 'Coherencia de certificados'), ('REGRESSION', 'Regresión'), ('HEALTH_RISK', 'Predicción de riesgo de salud'), ('LICENSE_APPROVAL', 'Aprobación de licencias'), ('REJECTION_REASON', 'Clasificación de motivo de rechazo')], max_length=50, verbose_name='Tipo de modelo'),
        ),
    ]
