# Generated by Django 3.2.25 on 2025-05-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('validation', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('required_days', models.PositiveIntegerField()),
                ('information', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('justified', models.BooleanField(default=False)),
                ('certificate_need', models.BooleanField(default=False)),
                ('certificate_immediate', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('min_advance_notice_days', models.IntegerField()),
                ('certificate_require', models.BooleanField(default=True)),
                ('tolerance_days_certificate_submission', models.IntegerField(blank=True, null=True)),
                ('total_days_granted', models.IntegerField(blank=True, null=True)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('yearly_approved_requests', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('missing_doc', 'Documentacion faltante'), ('pending', 'Pendiente de aprobacion'), ('rejected', 'Rechazada'), ('approved', 'Aprobada'), ('expired', 'Expirada')], max_length=100)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('evaluation_comment', models.TextField(blank=True, null=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='licenses.license')),
            ],
        ),
    ]
