# Generated by Django 4.2.21 on 2025-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20250516_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('missing_doc', 'Documentacion faltante'), ('pending', 'Pendiente de aprobación'), ('rejected', 'Rechazada'), ('approved', 'Aprobada'), ('expired', 'Expirada')], max_length=100),
        ),
    ]
