# Generated by Django 3.2.25 on 2025-05-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='certificate_immediate',
        ),
        migrations.RemoveField(
            model_name='license',
            name='certificate_need',
        ),
        migrations.RemoveField(
            model_name='license',
            name='justified',
        ),
    ]
