# Generated by Django 3.2.25 on 2025-05-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_auto_20250528_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='certificate_immediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='certificate_need',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='justified',
            field=models.BooleanField(default=False),
        ),
    ]
