# Generated by Django 3.2.25 on 2025-06-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_auto_20250528_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='certificate_immediate',
        ),
        migrations.RemoveField(
            model_name='license',
            name='certificate_need',
        ),
        migrations.RemoveField(
            model_name='license',
            name='justified',
        ),
    ]
