# Generated by Django 3.2.25 on 2025-06-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_auto_20250604_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='license',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='licenses.license'),
        ),
    ]
