# Generated by Django 3.2.25 on 2025-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_auto_20250604_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDatasetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('accidente_trabajo', 'Accidente de trabajo'), ('donacion_sangre', 'Donación de sangre'), ('duelo', 'Duelo tipo A y B'), ('enfermedad', 'Enfermedad'), ('asistencia_familiares', 'Asistencia de familiares'), ('estudios', 'Estudios'), ('matrimonial', 'Matrimonial'), ('mudanza', 'Mudanza'), ('gremial', 'Gremial'), ('nacimiento', 'Nacimiento'), ('salud_materna', 'Salud Materna'), ('vacaciones', 'Vacaciones'), ('otro', 'Otro')], max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
