# Generated by Django 3.2.25 on 2025-06-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_licensedatasetentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseDatasetEntry',
        ),
    ]
