# Generated by Django 3.2.25 on 2025-06-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250516_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfirstuser',
            name='is_telegram_suscriptor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthfirstuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
