# Generated by Django 3.2.25 on 2025-06-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250602_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_high_risk_department',
            field=models.BooleanField(default=False),
        ),
    ]
