# Generated by Django 3.2.25 on 2025-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250602_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfirstuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
